syntax = "proto3";
package patchbukkit.events;

import "patchbukkit/common/types.proto";
import "patchbukkit/events/block_events.proto";
import "patchbukkit/events/dialog_events.proto";
import "patchbukkit/events/enchantment_events.proto";
import "patchbukkit/events/entity_events.proto";
import "patchbukkit/events/hanging_events.proto";
import "patchbukkit/events/inventory_events.proto";
import "patchbukkit/events/player_events.proto";
import "patchbukkit/events/raid_events.proto";
import "patchbukkit/events/server_events.proto";
import "patchbukkit/events/vehicle_events.proto";
import "patchbukkit/events/world_events.proto";

option java_multiple_files = true;
option java_package = "patchbukkit.events";

message Event {
  oneof data {
    AsyncStructureGenerateEvent async_structure_generate = 1;
    AsyncStructureSpawnEvent async_structure_spawn = 2;
    ChunkLoad chunk_load = 3;
    ChunkPopulateEvent chunk_populate = 4;
    ChunkSave chunk_save = 5;
    ChunkSend chunk_send = 6;
    ChunkUnloadEvent chunk_unload = 7;
    EntitiesLoadEvent entities_load = 8;
    EntitiesUnloadEvent entities_unload = 9;
    GenericGameEvent generic_game = 10;
    LightningStrikeEvent lightning_strike = 11;
    LootGenerateEvent loot_generate = 12;
    PortalCreateEvent portal_create = 13;
    SpawnChangeEvent spawn_change = 14;
    StructureGrowEvent structure_grow = 15;
    TimeSkipEvent time_skip = 16;
    WeatherChangeEvent weather_change = 17;
    ThunderChangeEvent thunder_change = 18;
    WorldInitEvent world_init = 19;
    WorldLoadEvent world_load = 20;
    WorldUnloadEvent world_unload = 21;
    WorldSaveEvent world_save = 22;
    ServerListPingEvent server_list_ping = 23;
    MapInitializeEvent map_initialize = 24;
    PacketReceivedEvent packet_received = 25;
    PacketSentEvent packet_sent = 26;
    PluginDisableEvent plugin_disable = 27;
    PluginEnableEvent plugin_enable = 28;
    RemoteServerCommandEvent remote_server_command = 29;
    ServerBroadcastEvent server_broadcast = 30;
    ServerCommandEvent server_command = 31;
    ServerLoadEvent server_load = 32;
    ServerTickEndEvent server_tick_end = 33;
    ServerTickStartEvent server_tick_start = 34;
    ServiceRegisterEvent service_register = 35;
    ServiceUnregisterEvent service_unregister = 36;
    TabCompleteEvent tab_complete = 37;
    VehicleBlockCollisionEvent vehicle_block_collision = 38;
    VehicleCollisionEvent vehicle_collision = 39;
    VehicleCreateEvent vehicle_create = 40;
    VehicleDamageEvent vehicle_damage = 41;
    VehicleDestroyEvent vehicle_destroy = 42;
    VehicleEnterEvent vehicle_enter = 43;
    VehicleEntityCollisionEvent vehicle_entity_collision = 44;
    VehicleExitEvent vehicle_exit = 45;
    VehicleMoveEvent vehicle_move = 46;
    VehicleUpdateEvent vehicle_update = 47;
    BrewEvent brew = 48;
    BrewingStandFuelEvent brewing_stand_fuel = 49;
    CraftItemEvent craft_item = 50;
    FurnaceBurnEvent furnace_burn = 51;
    FurnaceExtractEvent furnace_extract = 52;
    FurnaceSmeltEvent furnace_smelt = 53;
    FurnaceStartSmeltEvent furnace_start_smelt = 54;
    HopperInventorySearchEvent hopper_inventory_search = 55;
    InventoryCreativeEvent inventory_creative = 56;
    InventoryDragEvent inventory_drag = 57;
    InventoryInteractEvent inventory_interact = 58;
    InventoryMoveItemEvent inventory_move_item = 59;
    InventoryOpenEvent inventory_open = 60;
    InventoryPickupItemEvent inventory_pickup_item = 61;
    PrepareAnvilEvent prepare_anvil = 62;
    PrepareGrindstoneEvent prepare_grindstone = 63;
    PrepareInventoryResultEvent prepare_inventory_result = 64;
    PrepareItemCraftEvent prepare_item_craft = 65;
    PrepareSmithingEvent prepare_smithing = 66;
    SmithItemEvent smith_item = 67;
    TradeSelectEvent trade_select = 68;
    BellResonateEvent bell_resonate = 69;
    BellRingEvent bell_ring = 70;
    BlockBreakEvent block_break = 71;
    BlockBrushEvent block_brush = 72;
    BlockBurnEvent block_burn = 73;
    BlockCanBuildEvent block_can_build = 74;
    BlockCookEvent block_cook = 75;
    BlockDamageEvent block_damage = 76;
    BlockDamageAbortEvent block_damage_abort = 77;
    BlockDispenseEvent block_dispense = 78;
    BlockDispenseArmorEvent block_dispense_armor = 79;
    BlockDispenseLootEvent block_dispense_loot = 80;
    BlockDropItemEvent block_drop_item = 81;
    BlockExpEvent block_exp = 82;
    BlockExplodeEvent block_explode = 83;
    BlockFadeEvent block_fade = 84;
    BlockFertilizeEvent block_fertilize = 85;
    BlockFormEvent block_form = 86;
    BlockFromToEvent block_from_to = 87;
    BlockGrowEvent block_grow = 88;
    BlockIgniteEvent block_ignite = 89;
    BlockMultiPlaceEvent block_multi_place = 90;
    BlockPhysicsEvent block_physics = 91;
    BlockPistonExtendEvent block_piston_extend = 92;
    BlockPistonRetractEvent block_piston_retract = 93;
    BlockPlaceEvent block_place = 94;
    BlockReceiveGameEvent block_receive_game = 95;
    BlockRedstoneEvent block_redstone = 96;
    BlockShearEntityEvent block_shear_entity = 97;
    BlockSpreadEvent block_spread = 98;
    BrewingStartEvent brewing_start = 99;
    CampfireStartEvent campfire_start = 100;
    CauldronLevelChangeEvent cauldron_level_change = 101;
    CrafterCraftEvent crafter_craft = 102;
    EntityBlockFormEvent entity_block_form = 103;
    FluidLevelChangeEvent fluid_level_change = 104;
    InventoryBlockStartEvent inventory_block_start = 105;
    LeavesDecayEvent leaves_decay = 106;
    MoistureChangeEvent moisture_change = 107;
    NotePlayEvent note_play = 108;
    SculkBloomEvent sculk_bloom = 109;
    SignChangeEvent sign_change = 110;
    SpongeAbsorbEvent sponge_absorb = 111;
    TNTPrimeEvent tnt_prime = 112;
    VaultDisplayItemEvent vault_display_item = 113;
    DialogClearEvent dialog_clear = 114;
    DialogClickActionEvent dialog_click_action = 115;
    DialogShowEvent dialog_show = 116;
    AsyncPlayerChatEvent async_player_chat = 117;
    AsyncPlayerPreLoginEvent async_player_pre_login = 118;
    BedrockFormResponseEvent bedrock_form_response = 119;
    PlayerChangedMainHandEvent player_changed_main_hand = 120;
    PlayerEggThrowEvent player_egg_throw = 121;
    PlayerExpChangeEvent player_exp_change = 122;
    PlayerFishEvent player_fish = 123;
    InventoryCloseEvent inventory_close = 124;
    InventoryClickEvent inventory_click = 125;
    PlayerItemHeldEvent player_item_held = 126;
    PlayerAdvancementDoneEvent player_advancement_done = 127;
    PlayerAnimationEvent player_animation = 128;
    PlayerArmorStandManipulateEvent player_armor_stand_manipulate = 129;
    PlayerBedEnterEvent player_bed_enter = 130;
    PlayerBedLeaveEvent player_bed_leave = 131;
    PlayerBucketEmptyEvent player_bucket_empty = 132;
    PlayerBucketFillEvent player_bucket_fill = 133;
    PlayerBucketEntityEvent player_bucket_entity = 134;
    PlayerChangeWorldEvent player_change_world = 135;
    PlayerChangedWorldEvent player_changed_world = 136;
    PlayerChannelEvent player_channel = 137;
    PlayerChatEvent player_chat = 138;
    PlayerCommandPreprocessEvent player_command_preprocess = 139;
    PlayerCommandSendEvent player_command_send = 140;
    PlayerCustomPayloadEvent player_custom_payload = 141;
    PlayerDropItemEvent player_drop_item = 142;
    PlayerEditBookEvent player_edit_book = 143;
    PlayerElytraBoostEvent player_elytra_boost = 144;
    PlayerExpCooldownChangeEvent player_exp_cooldown_change = 145;
    PlayerGamemodeChangeEvent player_gamemode_change = 146;
    PlayerHarvestBlockEvent player_harvest_block = 147;
    PlayerHideEntityEvent player_hide_entity = 148;
    PlayerInputEvent player_input = 149;
    PlayerInteractAtEntityEvent player_interact_at_entity = 150;
    PlayerInteractEntityEvent player_interact_entity = 151;
    PlayerInteractEvent player_interact = 152;
    PlayerInteractUnknownEntityEvent player_interact_unknown_entity = 153;
    PlayerItemBreakEvent player_item_break = 154;
    PlayerItemConsumeEvent player_item_consume = 155;
    PlayerItemDamageEvent player_item_damage = 156;
    PlayerItemMendEvent player_item_mend = 157;
    PlayerJoinEvent player_join = 158;
    PlayerKickEvent player_kick = 159;
    PlayerLeashEntityEvent player_leash_entity = 160;
    PlayerLeaveEvent player_leave = 161;
    PlayerLevelChangeEvent player_level_change = 162;
    PlayerLinksSendEvent player_links_send = 163;
    PlayerLocaleChangeEvent player_locale_change = 164;
    PlayerLoginEvent player_login = 165;
    PlayerMoveEvent player_move = 166;
    PlayerNameEntityEvent player_name_entity = 167;
    PlayerOpenSignEvent player_open_sign = 168;
    PlayerPermissionCheckEvent player_permission_check = 169;
    PlayerPickupArrowEvent player_pickup_arrow = 170;
    PlayerPortalEvent player_portal = 171;
    PlayerPreLoginEvent player_pre_login = 172;
    PlayerRecipeBookClickEvent player_recipe_book_click = 173;
    PlayerRecipeBookSettingsChangeEvent player_recipe_book_settings_change = 174;
    PlayerRecipeDiscoverEvent player_recipe_discover = 175;
    PlayerRegisterChannelEvent player_register_channel = 176;
    PlayerResourcePackStatusEvent player_resource_pack_status = 177;
    PlayerRespawnEvent player_respawn = 178;
    PlayerRiptideEvent player_riptide = 179;
    PlayerShearEntityEvent player_shear_entity = 180;
    PlayerShowEntityEvent player_show_entity = 181;
    PlayerSpawnChangeEvent player_spawn_change = 182;
    PlayerSpawnLocationEvent player_spawn_location = 183;
    PlayerStatisticIncrementEvent player_statistic_increment = 184;
    PlayerSwapHandItemsEvent player_swap_hand_items = 185;
    PlayerTakeLecternBookEvent player_take_lectern_book = 186;
    PlayerTeleportEvent player_teleport = 187;
    PlayerToggleFlightEvent player_toggle_flight = 188;
    PlayerToggleSneakEvent player_toggle_sneak = 189;
    PlayerToggleSprintEvent player_toggle_sprint = 190;
    PlayerUnleashEntityEvent player_unleash_entity = 191;
    PlayerUnregisterChannelEvent player_unregister_channel = 192;
    PlayerVelocityEvent player_velocity = 193;
    HangingBreakEvent hanging_break = 194;
    HangingBreakByEntityEvent hanging_break_by_entity = 195;
    HangingPlaceEvent hanging_place = 196;
    AreaEffectCloudApplyEvent area_effect_cloud_apply = 197;
    ArrowBodyCountChangeEvent arrow_body_count_change = 198;
    BatToggleSleepEvent bat_toggle_sleep = 199;
    CreatureSpawnEvent creature_spawn = 200;
    CreeperPowerEvent creeper_power = 201;
    EnderDragonChangePhaseEvent ender_dragon_change_phase = 202;
    EntityAirChangeEvent entity_air_change = 203;
    EntityBreakDoorEvent entity_break_door = 204;
    EntityBreedEvent entity_breed = 205;
    EntityChangeBlockEvent entity_change_block = 206;
    EntityCombustEvent entity_combust = 207;
    EntityCombustByBlockEvent entity_combust_by_block = 208;
    EntityCombustByEntityEvent entity_combust_by_entity = 209;
    EntityDamageEvent entity_damage = 210;
    EntityDamageByBlockEvent entity_damage_by_block = 211;
    EntityDamageByEntityEvent entity_damage_by_entity = 212;
    EntityDeathEvent entity_death = 213;
    PlayerDeathEvent player_death = 214;
    EntityDismountEvent entity_dismount = 215;
    EntityDropItemEvent entity_drop_item = 216;
    EntityDyeEvent entity_dye = 217;
    EntityEnterBlockEvent entity_enter_block = 218;
    EntityEnterLoveModeEvent entity_enter_love_mode = 219;
    EntityExhaustionEvent entity_exhaustion = 220;
    EntityExplodeEvent entity_explode = 221;
    EntityInteractEvent entity_interact = 222;
    EntityKnockbackEvent entity_knockback = 223;
    EntityKnockbackByEntityEvent entity_knockback_by_entity = 224;
    EntityMountEvent entity_mount = 225;
    EntityPickupItemEvent entity_pickup_item = 226;
    EntityPlaceEvent entity_place = 227;
    EntityPortalEvent entity_portal = 228;
    EntityPortalEnterEvent entity_portal_enter = 229;
    EntityPortalExitEvent entity_portal_exit = 230;
    EntityPoseChangeEvent entity_pose_change = 231;
    EntityPotionEffectEvent entity_potion_effect = 232;
    EntityRegainHealthEvent entity_regain_health = 233;
    EntityRemoveEvent entity_remove = 234;
    EntityResurrectEvent entity_resurrect = 235;
    EntityShootBowEvent entity_shoot_bow = 236;
    EntitySpawnEvent entity_spawn = 237;
    EntitySpellCastEvent entity_spell_cast = 238;
    EntityTameEvent entity_tame = 239;
    EntityTargetEvent entity_target = 240;
    EntityTargetBlockEvent entity_target_block = 241;
    EntityTargetLivingEntityEvent entity_target_living_entity = 242;
    EntityTeleportEvent entity_teleport = 243;
    EntityToggleGlideEvent entity_toggle_glide = 244;
    EntityToggleSwimEvent entity_toggle_swim = 245;
    EntityTransformEvent entity_transform = 246;
    EntityUnleashEvent entity_unleash = 247;
    ExpBottleEvent exp_bottle = 248;
    ExplosionPrimeEvent explosion_prime = 249;
    FireworkExplodeEvent firework_explode = 250;
    FoodLevelChangeEvent food_level_change = 251;
    HorseJumpEvent horse_jump = 252;
    ItemDespawnEvent item_despawn = 253;
    ItemMergeEvent item_merge = 254;
    ItemSpawnEvent item_spawn = 255;
    LingeringPotionSplashEvent lingering_potion_splash = 256;
    PigZapEvent pig_zap = 257;
    PigZombieAngerEvent pig_zombie_anger = 258;
    PiglinBarterEvent piglin_barter = 259;
    PotionSplashEvent potion_splash = 260;
    ProjectileHitEvent projectile_hit = 261;
    ProjectileLaunchEvent projectile_launch = 262;
    SheepDyeWoolEvent sheep_dye_wool = 263;
    SheepRegrowWoolEvent sheep_regrow_wool = 264;
    SlimeSplitEvent slime_split = 265;
    SpawnerSpawnEvent spawner_spawn = 266;
    StriderTemperatureChangeEvent strider_temperature_change = 267;
    TrialSpawnerSpawnEvent trial_spawner_spawn = 268;
    VillagerAcquireTradeEvent villager_acquire_trade = 269;
    VillagerCareerChangeEvent villager_career_change = 270;
    VillagerReplenishTradeEvent villager_replenish_trade = 271;
    VillagerReputationChangeEvent villager_reputation_change = 272;
    WardenAngerChangeEvent warden_anger_change = 273;
    RaidFinishEvent raid_finish = 274;
    RaidSpawnWaveEvent raid_spawn_wave = 275;
    RaidStopEvent raid_stop = 276;
    RaidTriggerEvent raid_trigger = 277;
    EnchantItemEvent enchant_item = 278;
    PrepareItemEnchantEvent prepare_item_enchant = 279;
  }
}

message FireEventResponse {
  bool cancelled = 1;
  Event data = 2;
}

message CallEventRequest {
  Event event = 1;
}

message CallEventResponse {
  FireEventResponse response = 1;
}

message RegisterEventRequest {
  string event_type = 1;
  string plugin_name = 2;
  int32 priority = 3;
  bool blocking = 4;
}
